version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    command: node server.js
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/financeapp
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

volumes:
  mongo-data: